export {
  DEFAULT_PAGE_MOTION,
  DEFAULT_SECTION_MOTION,
  extractPageMotionFromHomeSections,
  formatSectionMotionSummary,
  HEAVY_SECTION_MOTION_DEFAULTS,
  HOMEPAGE_PAGE_CONFIG_KEY,
  MOTION_INTENSITY_OPTIONS,
  MOTION_PRESET_OPTIONS,
  MOTION_PRESETS,
  MOTION_STAGGER_OPTIONS,
  PAGE_MOTION_INTENSITY_OPTIONS,
  PAGE_MOTION_PRESET_OPTIONS,
  normalizePageMotion,
  normalizeSectionMotion,
  resolveSectionMotion,
  toEnterMotionBinding,
  toFramerMotionProps,
  toWhileInViewBinding,
  type EnterMotionBinding,
  type WhileInViewMotionBinding,
  type MotionIntensity,
  type MotionPreset,
  type MotionStaggerMode,
  type PageMotionConfig,
  type PageMotionIntensity,
  type PageMotionPreset,
  type ResolvedMotionConfig,
  type SafeMotionProps,
  type SectionMotionConfig,
} from './motion';

export { useSectionMotion, type UseSectionMotionOptions } from './useSectionMotion';
