export {
  DEFAULT_PAGE_MOTION,
  DEFAULT_SECTION_MOTION,
  extractPageMotionFromHomeSections,
  formatSectionMotionSummary,
  HEAVY_SECTION_MOTION_DEFAULTS,
  HOMEPAGE_PAGE_CONFIG_KEY,
  MOTION_INTENSITY_OPTIONS,
  MOTION_PRESET_OPTIONS,
  MOTION_PRESETS,
  MOTION_STAGGER_OPTIONS,
  PAGE_MOTION_INTENSITY_OPTIONS,
  PAGE_MOTION_PRESET_OPTIONS,
  normalizePageMotion,
  normalizeSectionMotion,
  resolveSectionMotion,
  toEnterMotionBinding,
  toFramerMotionProps,
  toWhileInViewBinding,
  type EnterMotionBinding,
  type WhileInViewMotionBinding,
  type MotionIntensity,
  type MotionPreset,
  type MotionStaggerMode,
  type PageMotionConfig,
  type PageMotionIntensity,
  type PageMotionPreset,
  type ResolvedMotionConfig,
  type SafeMotionProps,
  type SectionMotionConfig,
} from './motion';

export { useSectionMotion, type UseSectionMotionOptions } from './useSectionMotion';

export {
  BASELINE_THEME_TOKENS,
  DEFAULT_PAGE_THEME,
  DEFAULT_SECTION_THEME,
  SECTION_THEME_PRESET_OPTIONS,
  THEME_PRESET_IDS,
  THEME_PRESET_OPTIONS,
  THEME_PRESET_OVERRIDES,
  THEME_TOKEN_ADMIN_OPTIONS,
  THEME_TOKEN_CSS_VARS,
  THEME_TOKEN_KEYS,
  collectThemeSaveValidation,
  extractPageThemeFromHomeSections,
  formatSectionThemeSummary,
  getThemeTokenMappingTable,
  isContrastAcceptable,
  normalizePageTheme,
  normalizeSectionTheme,
  resolveSectionThemeTokens,
  sanitizeThemeTokenOverrides,
  themeTokensToCssVars,
  themeTokensToStyle,
  validateThemeToken,
  type ColorMode,
  type PageThemeConfig,
  type PageThemePreset,
  type ResolvedThemeTokens,
  type SectionThemeConfig,
  type SectionThemePreset,
  type ThemePreset,
  type ThemeTokenConfig,
  type ThemeTokenKey,
  type ThemeSaveValidation,
} from './theme';

export {
  shouldApplySectionTheme,
  useSectionTheme,
  useThemeColorMode,
} from './useSectionTheme';
